### ISSUE TITLE
NetworkError: 401 Unauthorized on basic auth protected sites

### ISSUE THREAD

**Issue by X-Coder** [spenibus/cors-everywhere-firefox-addon#1]
Hi, I like your addon, but I have some issue with it on a basic auth protected site.

When I try to connect to this site, firefox asks me for the credentials, which I enter correctly.
The site loads, but without all the font resources, which are also protected by this login. The .js and .css resources are working.

I can see lots of NetworkError: 401 Unauthorized - %URL_OF_RESOURCE% messages in firebug for resources like .woff, .eot, and .ttf.

When I try to access the font resources directly (after I logged in), it works too.

A quick search (http://davidwalsh.name/cdn-fonts) revealed that the Access-Control-Allow-Origin header maybe need to be injected into the response header for the fonts too, which is currently not happening.

Is this 401 error a problem within your addon, or firefox?

**Comment by spenibus** [comment]
The injection of the CORS headers into the response is post-processing, it only makes Firefox believe that the server has sent the necessary headers to bypass the security restrictions. It should not affect the http transaction itself.

When the request is rejected because of the same origin policy, the web console gives a security type message such as follows:
"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at %URL%. This can be fixed by moving the resource to the same domain or enabling CORS."

The errors 401 suggest the server does not see you as an authenticated user when you try to access the fonts, which doesn't seem related to CORS.

Anyway, questions:
1. Are the fonts files on the same server and dir/subdir as the html/css/js files, protected by the same .htpasswd ? I mean literally the same .htpasswd, not a copy in a different folder.
2. If you login to access the html and then access a font directly, does it work right away or do you have to login again ?
3. Is the server running IIS ?

**Comment by X-Coder** [comment]
Thank you for the answer. 

I have a feeling that the company has a misconfiguration in their remote server. Nothing you can fix, I first thought it could be related to CORS, but my mind changed.

> 1. Are the fonts files on the same server and dir/subdir as the html/css/js files, protected by the same .htpasswd ? I mean literally the same .htpasswd, not a copy in a different folder.

I only manage the server that hosts the html, the one that is protected is the remote one which delivers the fonts, css, and js resources. So I can't say anything about the remote's internals and can't answer the question about the htpasswd file. The font files are in different subfolders than css/html/js.

I was wrong about the the .js resources. It only worked because the js resources were loaded directly in head by a script tag. I just tried to load the same resources using javascript with $.get(), and now I will get a 401 status error for this too and a user defined response body which has is 404 page, but if I call the same url directly, I can fetch the resource just fine. The fonts that are failing with 401 gets loaded by a external css file from the same domain, port and protocol were the css file is hosted. I included this external css in a link tag in head.

The only thing different is that all failed resources which gets loaded by $.get()  or by the external css have this 401 status and a 'WWW-Authenticate: Basic realm="..."' header in the response. The realm matches the one that is shown in the credential dialog.

With your addon disabled I get the 401 access denied error and the "Cross-Origin Request Blocked" warning in console for the fonts and js, if I enable your addon the "Cross-Origin Request Blocked" warning goes away, but the 401 stays. When your addon is enabled I can see in the response header how your addon is inserting the Access-Control-Allow-Origin header for both, the js and the fonts.

> 1. If you login to access the html and then access a font directly, does it work right away or do you have to login again ?

I just need to login once to access the html, then I can access the fonts or js directly without a password question.

> 1. Is the server running IIS ?

No, both are running Apache 2.4.

**Comment by spenibus** [comment]
So I've been experimenting with http basic auth and cross domain requests.

Both Firefox and Chrome do not send the "Authorize: Basic xxx" header that carries the credentials when fetching a font from another domain with a css font-face rule. So even with the proper CORS headers, the request will still fail with an error 401. In fact, when setting the style directly in the html document, I am never prompted for credentials to access the font file.

This is not something that can be solved with a cors header override.

Javascript fetch.
You should be able to send credentials along the request. The jquery docs should provide some answers.

Css web fonts.
The only solution I can think of would be to use the extension "Modify Headers", available here:
https://addons.mozilla.org/en-US/firefox/addon/modify-headers/
and inject the "Authorize" header. You can find its value by looking at the request for the css file.
This should likely apply to javascript fetch calls as well.

I don't think there is much more I can do.

**Comment by t-nelis** [comment]
For the record, the fonts fetching behavior seems consistent with [the spec](http://www.w3.org/TR/2013/CR-css-fonts-3-20131003/#font-fetching-requirements):

> When fetching, user agents must use "Anonymous" mode [...]

Depending on the implementation, forcing the addition of an `Authorize` header via extensions might not work, and in any case wouldn't be standard behavior _as I interpret it_.

I haven't found any rationale for this behavior, it could be an oversight.

**Comment by spenibus** [comment]
It's unlikely the server would care though. Nor the client, considering it can be tricked regarding cors. I tested the injection of the "Authorize" header and got access to the font, so it's at least possible.

**Comment by X-Coder** [comment]
Thank you for your hint with the modify header addon, adding the Authorization header did the trick.
