### ISSUE TITLE
CORS everywhere is not a webextension

### ISSUE THREAD

**Issue by kubrickfr** [spenibus/cors-everywhere-firefox-addon#12]
As of today, FF nightly disables this addon automatically because it's not a web extension...

**Comment by spenibus** [comment]
I would have to check if the new framework supports this, and I'm not too confident about it.

**Comment by HarlemSquirrel** [comment]
This is now disabling Multiprocess

**Comment by spenibus** [comment]
My schedule opened a little, this might be doable. Looks like WebExtension APIs also actually have everything I need for this.

**Comment by spenibus** [comment]
Addon is now a WebExtension. Basic testing shows no issue. Awaiting review on AMO.

I haven't tested multi process though.

**Comment by spenibus** [comment]
Quickly enabled multiprocess and I heard no sirens in the distance. CORS still bypassed while multiple processes for a single window are visible in the task manager.

**Comment by spenibus** [comment]
Not quite sure how but it went through the review process rather quickly.

https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/
