### ISSUE TITLE
Add Enabled/Disabled to tooltip of  CorsE button

### ISSUE THREAD

**Issue by klahnakoski** [spenibus/cors-everywhere-firefox-addon#14]
The "CorsE" button is currently a pink color, but I have no idea what that means.  When I hover over the button the tooltip says "CorsE"; please change it to include "enabled" or "disabled".

**Comment by klahnakoski** [comment]
Example:

![image](https://user-images.githubusercontent.com/2334429/29894748-7ee94f28-8da4-11e7-9bec-3cdbf46e401b.png)

**Comment by klahnakoski** [comment]
Even "enabled" and "disabled" may be bad choices: Does "enabled" mean cors headers rules are followed?

**Comment by spenibus** [comment]
I do remember thinking I should tamper with the hovering label when I completed the WebExtension transition. Done whenever I find a minute.

The states (enabled/disabled) are relative to the addon. An enabled addon will bypass CORS.

Planned labels:
- CorsE disabled, CORS rules are followed
- CorsE enabled, CORS rules are bypassed

**Comment by spenibus** [comment]
Oh yeah, fixed in 2882a82dce660e56f50577ab9854eb8d9c6f7128.
