### ISSUE TITLE
New Feature: Configure Origin header

### ISSUE THREAD

**Issue by michaelschneiderdaimler** [spenibus/cors-everywhere-firefox-addon#17]
Hi spenibus,

in order to test in more complex environments, I would suggest adding a configurable "Origin" header to the requests.

Thanks!
-michael

**Comment by spenibus** [comment]
Option added in 965482b616480a3dd84a6330691c6714572cbfec.
Might need refining if I misunderstood the idea.

**Comment by spenibus** [comment]
Build is available here:
[cors-everywhere@spenibus-18.3.8.2053.xpi](http://spenibus.net/files/gitbin/cors-everywhere-firefox-addon/cors-everywhere@spenibus-18.3.8.2053.xpi)
