### ISSUE TITLE
Doesn't work on Firefox 59 on a Mac

### ISSUE THREAD

**Issue by Medtrack** [spenibus/cors-everywhere-firefox-addon#18]
This addon doesn't seem to work on Firefox 59 on MacOS.
Attached you can find a screenshot with the console output on Firefox and on Chrome. You can see in the screenshot that the request is blocked on firefox and works on Chrome.

I disabled Cors on Chrome running it with this command:

```
"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"  --disable-web-security --user-data-dir=/Users/mac/chromeprof  --allow-running-insecure-content --allow-file-access-from-files
```

![cors-firefox-chrome](https://user-images.githubusercontent.com/17614549/37709409-674d8f0e-2d0a-11e8-9c1c-9aff449b0c75.png)

I modified the file _cors-everywhere-html_ this way:
```
var xhr = new XMLHttpRequest();
            xhr.open("get", "http://google.com", true);
            xhr.withCredentials = true;
            xhr.onreadystatechange = function(r) {
                document.getElementById("response").innerHTML +=
                    "<hr />readyState: "+r.target.readyState+
                    "<br />status: "+r.target.status;
                    
                    if (this.readyState == 4 && this.status == 200) {
                        console.log(this.responseText);
                        console.log(this)
                        console.log(r)
                      }
            }
            xhr.send();
```

**Comment by spenibus** [comment]
I'm not seeing the addon's button on the toolbar. Did you activate the addon using the button after installing it ?

**Comment by bwurtz999** [comment]
I'm having the same issue. Firefox updated automatically today and now I can't connect to my local server. I've been using the add-on for months without issue until today.

**Comment by bwurtz999** [comment]
I went back and reinstalled the previous version of Firefox and disabled auto updates and now it works fine (for anyone who needs a quick fix).

**Comment by spenibus** [comment]
Regarding this [comment][1]:
> I'm having the same issue. Firefox updated automatically today and now I can't connect to my local server. I've been using the add-on for months without issue until today.

I do wonder if the installed addon was still the XUL version and Firefox updated to a WebExtension only version of itself (Quantum if I recall correctly). I remember a conversation where someone didn't get the updated addon when it was turned into a WebExtension.

It really wouldn't hurt to add which version of the addon is being used when submitting these bug reports.

[1]: https://github.com/spenibus/cors-everywhere-firefox-addon/issues/18#issuecomment-375103649

**Comment by bwurtz999** [comment]
Sorry, forgot to add that. My extension is named CORS Everywhere 17.7.16.1852, last updated today (March 21, 2018).

Also, I went from release 59 of Firefox back to 58.0.2.

**Comment by spenibus** [comment]
Preliminary testing on my end of `Firefox 59.0.1` + `CORS Everywhere 17.7.16.1852` shows no apparent issue. The test page returns the expected results.

**Comment by Medtrack** [comment]
It keeps failing on my computer. The button is in the top bar and enabled.
There's a message in the console in Spanish. It says this: "_Request from another origin blocked: the same origin policy disallows reading the remote resource in ....._ ".

It's version 17.7.16.1852 from firefox addon page. If I have time, I will try to debug later.
![pantallazo](https://user-images.githubusercontent.com/17614549/37759725-bfdf59f4-2db4-11e8-9e25-4674fcd3b69e.png)

**Comment by Medtrack** [comment]
Ok. I found the issue!!! My fault.
Thank you very much for your job!
Sorry for the inconvenience.
The problem was that I have the [Duckduckgo Privacy Essentials addon](https://addons.mozilla.org/es/firefox/addon/duckduckgo-for-firefox/) and it looks like that plugin blocks this one.
I can disable that plugin and it works.
![captura de pantalla 2018-03-22 a las 9 49 56](https://user-images.githubusercontent.com/17614549/37760259-6f1eadce-2db6-11e8-8030-6181bf72193e.png)
