### ISSUE TITLE
Feature request: per host activation

### ISSUE THREAD

**Issue by gentunian** [spenibus/cors-everywhere-firefox-addon#19]
Sometimes I may forgot this add on is enabled and it may be a security risk for my daily browsing.

It would be nice to have a feature to enable this addon per host. This way, CORS will be disabled only for custom domain/hosts, e.g. "localhost:4444" or "my.example.com" etc.

**Comment by spenibus** [comment]
Similar to #7, will try to finally work on it.
Although to make my life easier it will probably be a regex filter on host url, which should prove more versatile anyway.

**Comment by spenibus** [comment]
Note that this feature might have a potential performance impact since the addon remains active and each request has to be checked against the whitelist.

**Comment by gentunian** [comment]
@spenibus makes sense. I think that the feature should be optional. It would be worse to let undesired requests to be CORSed.

**Comment by spenibus** [comment]
Of course, host detection is a secondary step. You still need to enable the addon first.

**Comment by spenibus** [comment]
Implemented since 0ffa51ee088f58c44fb0257916f9a231a03d8976.

**Comment by gentunian** [comment]
good work! :)

**Comment by spenibus** [comment]
Version 18.5.30.1913 has been pushed to AMO. [CORS Everywhere on AMO][1]

[1]: https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/
