### ISSUE TITLE
Incorrect saving settings by default

### ISSUE THREAD

**Issue by maxtar** [spenibus/cors-everywhere-firefox-addon#21]
**Step to reproduce:**

1. Install addon.
2. Open addon setting.
1. Press save button.
1. Disable/enable addon.

**Actual result:**
CORS doesn't works because _"Force value "acess-control-allow-origin""_ saved as undefined.

**Expected result:**
Option _"Force value "acess-control-allow-origin""_ need to saves as _empty_.

**Comment by spenibus** [comment]
Actually a loading issue where the non-existing pref is `undefined`, which is then converted to string on display and gets saved if one decides to press the save button without clearing the input.

Fixed in ca43390c7be25521fd89a0b7e8df88cf2bb34d58, officially version `18.11.13.2043`.
