### ISSUE TITLE
I‘m sorry to say that didnot work on win7-63.0.3 (64 bit)

### ISSUE THREAD

**Issue by liliangce** [spenibus/cors-everywhere-firefox-addon#22]
I install the addon by WebExtensions markets.  and more the corsE button changes to green .
finally I get info:已拦截跨源请求：同源策略禁止读取位于 https://10.93.133.45:28001/api/sta-subscriber/v1/event/region?traceType=CELL&language=zh-CN&csrftoken=null 的远程资源。（原因：CORS 预检通道未成功）(it means cors Preview channel falid)

**Comment by spenibus** [comment]
A preflight request can fail for many reasons even when the addon is enabled. And without any code, it will be pretty much impossible to investigate.

First, make sure that the resource returns a 2xx http code. Other codes will fail the preflight as per the spec:

> 7.1.5 Cross-Origin Request with Preflight
> ...
> If the response has an HTTP status code that is not in the 2xx range:
> Apply the network error steps.

[Cross-Origin Resource Sharing - W3C Recommendation 16 January 2014][1]

[1]: https://www.w3.org/TR/2014/REC-cors-20140116/#cross-origin-request-with-preflight-0

**Comment by spenibus** [comment]
Note: I must change the title when GitHub stops bugging out.

> Preflight request failure (win7 - 63.0.3 - 64 bit)
