### ISSUE TITLE
Whitelist docs unclear

### ISSUE THREAD

**Issue by pickfire** [spenibus/cors-everywhere-firefox-addon#23]
CORS everywhere plugin looks great but I still don't get how to use whitelist after reading what it mentioned there. Do I do?

```
domain.tld
https://domain.tld
/^https?...localhost:8080\//i
https?...localhost:8080
*
domain.tld/path
https://domain.tld/path
localhost:8080
```
Do I put in the `localhost:8080` that I do development on or the `server/path` that the site calls?

**Comment by spenibus** [comment]
It's the origin (the caller) that must be whitelisted. Let's say you have a script on localhost calling the Twitch API, you would whitelist localhost (the caller) and not Twitch (the callee).

Also it must be a fully qualified regular expression, with delimiters and flags, e.g.:

`/^https?...localhost:8080\//i` or the less strict `/localhost:8080/i` 

Note that it is also preferable to disable the addon when you're done working. When using the whitelist, the addon still has to check each request made by the browser and decide whether or not to intervene.

If I ever have the time, this will be rewritten to use two whitelists, one for the origin and one for the target. This would close issue #2.

**Comment by pickfire** [comment]
Yeah, I just figured out later so I do `/localhost:8080/path`. Ah, so I need to disable it when not working, usually I just disable the whole add-on (not sure if that will save power).

Should I close this issue?

**Comment by spenibus** [comment]
Don't forget to escape the slashes within the path.

You don't need to disable the addon but you're wasting a few CPU cycles when it's active (the magnitude of that load depends on your browser's network activity), so unless you actively require it, there is no benefit to having it enabled. It's likely unnoticeable but why risk it.

If you think your issue has been resolved, feel free to close.

**Comment by pickfire** [comment]
Thanks a lot! :smile:
