### ISSUE TITLE
Adding a file:// ressource to the activation whitelist doesn't seem to work

### ISSUE THREAD

**Issue by rlesch** [spenibus/cors-everywhere-firefox-addon#24]
even a " .* " doesnt trigger it.

**Comment by spenibus** [comment]
The whitelist takes fully qualified regular expressions, e.g.:

````
/.*/
/^file:/i
````

I have also just tested a local copy of [my CORS test][1] with the filter `/^file:/i` and that worked fine while the one I host online was still blocked as expected.

If your problem persists, you might want to detail your specific scenario so I can investigate further.

[1]: http://spenibus.net/cors-everywhere-test.html
