### ISSUE TITLE
Won't work with Firefox 65.0.1 Mac

### ISSUE THREAD

**Issue by SebCorbin** [spenibus/cors-everywhere-firefox-addon#26]
On localhost:3000 or production server (react app), I'm unable to load a map because of CORS 

```
Error: "NetworkError when attempting to fetch resource."
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.mapbox.com/styles/v1/mapbox/streets-v9?access_token=... (Reason: CORS request did not succeed).
```

Other external requests work well, the request with curl returns 

```
curl -i https://api.mapbox.com/styles/v1/mapbox/streets-v9\?access_token\=...
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 88004
Connection: keep-alive
Date: Thu, 28 Feb 2019 15:26:55 GMT
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Link
Cache-Control: max-age=900
ETag: W/"157c4-NRKsvljOL2AA19XRL9Bm2yG3wnk"
Vary: Accept-Encoding
X-Cache: Miss from cloudfront
Via: 1.1 15915c6842263dc42a906b5361d7d566.cloudfront.net (CloudFront)
X-Amz-Cf-Id: UF0U0FOvHNAVGPGSl6u5E7V_7A-0385PbNEQt8S6MbTLq7vQBbsbeg==
```

Don't hesitate to ask for further details, the page works well with Chromium or Safari (without any extension), which is weird

**Comment by spenibus** [comment]
1. Using withCredentials ?
2. What http code is returned in Firefox for that request ?
3. Does your Firefox pass the basic test ?
   http://spenibus.net/cors-everywhere-test.html

**Comment by SebCorbin** [comment]
After a reset of my Firefox, it works again, sorry for the bothering...

Turns out it was a problem with Ghostery, altering the request, but not updating its tracker list. Trusting the site is fixing the issue.

**Comment by spenibus** [comment]
Neat, less work.

**Comment by spenibus** [comment]
Actually, this is helpful for future issues. I never considered interferences from other addons, so that's one more question to put on the checklist. Well done, you.
