### ISSUE TITLE
Issue with Brightcove media players

### ISSUE THREAD

**Issue by ghost** [spenibus/cors-everywhere-firefox-addon#28]
After much searching I read that "CORS everywhere" addon might fix this bug for me - it has not.

Brightcove players seem totally broken in Firefox, spitting out:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://secure.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=2026635565001&secure=true&pubId=1752604059001&videoId=2026627037001. (Reason: CORS header 'Access-Control-Allow-Origin' missing).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://secure.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=2026635565001&secure=true&pubId=1752604059001&videoId=2026627037001. (Reason: CORS request did not succeed).[Learn More]` in the console.

See here: https://support.brightcove.com/brightcove-player-sample-are-you-still-watching

**Comment by spenibus** [comment]
Honestly, there isn't enough information for me to reproduce the issue.

I tried the example code on the page you linked and it worked fine on its own, both locally and remotely.

The trouble might come from your specific setup and I can't magically guess what it is.

Also, after installing the addon, did you turn it on by clicking on the button to make it green ?

**Comment by ghost** [comment]
Does `AbortError: The fetching process for the media resource was aborted by the user agent at the user's request.` shed any light?

**Comment by spenibus** [comment]
Sadly, no. This might actually be a consequence of the request being blocked.

**Comment by ghost** [comment]
Seems like an actual bug in Firefox, confirmed by the Bugzilla guys - feel free to close!
