### ISSUE TITLE
Call keep returning Status 0

### ISSUE THREAD

**Issue by edu-faria** [spenibus/cors-everywhere-firefox-addon#34]
Hello,

first of all, thank you for providing such a good tool.

Even when I turn the extension on, Firefox returns me a CORS error (and the status of the call is 0).
The test page returns me the status 200. I am using Firefox 75.0. See attachments:

![image](https://user-images.githubusercontent.com/62955058/81071612-408f2780-8ee5-11ea-8b3c-f36fd829caf6.png)

I did rewrite my call in order to keep it close to the example page:

![image](https://user-images.githubusercontent.com/62955058/81071777-78966a80-8ee5-11ea-8d0d-2eb05ce8a318.png)

Is any incompatibility with some endpoints?

Thank you very much

**Comment by spenibus** [comment]
Sadly, [Reason: CORS request did not succeed][1] is pretty much the most generic error to hit.

I assume you tried other urls from your setup and they work.
Perhaps the server doesn't like the request, it could be malformed in some way, maybe withCredentials creates an authentication issue.

Best chance is if you have access to the server and can monitor the entire exchange.

But honestly, I just don't have a solution at hand for this, there are too many possibilities.

[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed
