### ISSUE TITLE
Chromium support

### ISSUE THREAD

**Issue by rajkumaar23** [spenibus/cors-everywhere-firefox-addon#37]
Hey! Great work on the extension! 
Do you have any idea of making this available on chrome web store? Asking because most of the extensions I checked were setting wildcard header.
Please direct me if there’s an equal alternative of this in Chrome Web Store.

**Comment by spenibus** [comment]
Chromium has `--disable-web-security` which doesn't exist on Firefox and is the only reason this addon even exist in the first place, so it's unlikely to be ported there. I don't use that browser so I can't really help you with that.
