### ISSUE TITLE
Extension is not working for file:// url under Firefox 78

### ISSUE THREAD

**Issue by jbarotin** [spenibus/cors-everywhere-firefox-addon#38]
Hi,

If I'm open a local static html page in my browser (Firefox 78.0) with your plugin in enabled with the following code :
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
  <head>
    <meta charset="UTF-8">
    <script>
      // Vanilla
      var httpRequest = new XMLHttpRequest();
      httpRequest.onreadystatechange = function(data) {
        
      };
      httpRequest.open("GET", "test.txt");
      httpRequest.send();
    </script>
  </head>
  <body>
  </body>
</html>
```

It generates the following message in the console :

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/jerome/Drive/Perso/2020/07_cors_firefox78/test.txt. (Reason: CORS request not http).`

https://developer.mozilla.org/fr/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

**Comment by spenibus** [comment]
You can try this:

[Cross-Origin Request Blocked when loading local file][1]

`privacy.file_unique_origin` = `false`
`security.fileuri.strict_origin_policy` = `false`

But no guarantee.

[1]: https://stackoverflow.com/a/57125361/3512867

**Comment by jbarotin** [comment]
I just checked with firefox 78.0.2... and now it works. I close the issue.
