### ISSUE TITLE
[Issue-Type: Query] -- Issue implementing similar functionality for a specific ping, using Firefox WebExtension APIs 

### ISSUE THREAD

**Issue by ghost** [spenibus/cors-everywhere-firefox-addon#4]
below is part of my background.js which implements this

//------- in file background.js

```
chrome.webRequest.onHeadersReceived.addListener(addHeadersToIntegrator,
    {
        urls: ['https://my.url.io/*'], // Pattern to match all http(s) pages
        types: ['sub_frame', 'main_frame', "xmlhttprequest", "script", "object", "other"]
    },
    ['blocking', 'responseHeaders']
);

chrome.webRequest.onBeforeSendHeaders.addListener(resetOrigin,
    {
        urls: ["https://my.url.io/*"],
        types: ["main_frame", "sub_frame", "xmlhttprequest", "script", "object", "other"]
    },
    ["blocking", "requestHeaders"]
);

```

In callbacks, I am changing the 'origin' header of request to 'https://a.url.com' and also changing the 'access-control-allow-origin' to 'https://a.url.com'. 

This changing of headers is working properly but still getting cross-domain error.

Other details: Firefox Developer Edition, Version 46

**Comment by spenibus** [comment]
I'm not familiar with the WebExtensions API. I'll run a few tests when I find some time.

**Comment by ghost** [comment]
I strongly think that problem is with webExtension API.. I am able to implement using addin sdk. I see that you have a ToDo similar to this... Will raise a PR for that... Thanks for your reply

**Comment by spenibus** [comment]
Since the addon is now using the WebExtension API, I think I can close this.
