### ISSUE TITLE
Various issues on linux firefox 86.0b4

### ISSUE THREAD

**Issue by apiraino** [spenibus/cors-everywhere-firefox-addon#42]
Hi!

I am a Firefox beta user and I remember I have used this nice extension just a couple of months ago.

I've tried using it these days with the latest firefox beta and I notice that:
1) on a fresh installation of the addon, the icon does not show up anymore
2) the extension options are not visible anymore
3) the test page fails even if the extension _should_ be enabled (cant really check because I don't see the icon)

If I debug the extension I see this error in the console (not sure it's related)
![grafik](https://user-images.githubusercontent.com/6098822/106523727-d641fc80-64e1-11eb-8b5e-324f25475964.png)

Any help?

thanks!

**Comment by apiraino** [comment]
Additional info: I cloned this repository to investigate the issue. I've compiled and run the extension locally, opened in a new firefox profile with: `web-ext run --browser-console --target=firefox-desktop` and the extension works :thinking: 

I think I'm going to close this issue because I cannot reproduce the issue reliably (on some firefox profiles it works, on others don't). Sorry for the noise.

happy to receive feedback, though.

**Comment by spenibus** [comment]
Gotta admit it feels like a beta bug. As far as that log goes, assuming it is even related, the profile folder isn't really something that would be handled by the addon, especially in the age of WebExtensions.

We'll see if more people start complaining I guess.
