### ISSUE TITLE
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true. (Reason: CORS request did not succeed).  ​

### ISSUE THREAD

**Issue by arch-user-france1** [spenibus/cors-everywhere-firefox-addon#49]
I tried with red corse symbol and green corse symbol. 

It's an html file (index.html) opened by firefox index.html

**Comment by spenibus** [comment]
Bug report too low on details.

Still, I tried the test page with the url and it seems to works. Not much more I can do at this point.

[cors-everywhere-test](http://spenibus.net/cors-everywhere-test.html)
````
readyState: 2
status: 200
readyState: 3
status: 200
readyState: 4
status: 200
````

**Comment by arch-user-france1** [comment]
Could it be a mistake by the code? Prob. not

Does corse work with files? Like: firefox <file.html>

**Comment by spenibus** [comment]
The test page is a html file that can run locally if downloaded, it works.

**Comment by arch-user-france1** [comment]
The problem is that I don't need it anymore at the moment so if you think that the plugin's fine, close the issue.
