### ISSUE TITLE
Response ignores login sessions

### ISSUE THREAD

**Issue by julkue** [spenibus/cors-everywhere-firefox-addon#5]
Say you are trying to load a website like `github.com` and you are logged in on that site, then you will get a response like if you would visit the website not logged in.

**Comment by spenibus** [comment]
Are you using [`XMLHttpRequest.withCredentials`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) ?

The following code returns this issue's page with me logged in:

```
var u = 'https://github.com/spenibus/cors-everywhere-firefox-addon/issues/5';

function reqListener () {
    console.log(this.responseText);
}

var xhr = new XMLHttpRequest();
xhr.addEventListener("load", reqListener);
xhr.open("GET", u);
xhr.withCredentials = true;
xhr.send();
```

**Comment by julkue** [comment]
No, I didn't used something like that. I'm using jQuery, so I would need to set:

``` javascript
$.ajax({
   xhrFields: {
      withCredentials: true
   }
});
```

I can't test it at the moment. However, I'm quite sure that this will fix the issue, so I'll close it for now and reopen it if it doesn't work.
