### ISSUE TITLE
Add support of `Access-Control-Allow-Credentials: true` header

### ISSUE THREAD

**Issue by linev** [spenibus/cors-everywhere-firefox-addon#55]
This should allow to use `XMLHttpRequest` with `withCredentials = true` flag without need to retype password any time new browser session / new browser tab is started.

Some discussion can be found here:

https://stackoverflow.com/questions/24687313

To use this feature, one should configure following fields in the response header:
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: exact_origin_url
```

It is not enough to specify `*` as origin, in this case cookie will be rejected.

**Comment by spenibus** [comment]
Hmm, forgot this ticket...

Anyway, as far as I remember, this is already what the addon is supposed to do.

We set the `access-control-allow-origin` with the `origin` value (which has priority over `*`) at line [254](https://github.com/spenibus/cors-everywhere-firefox-addon/blob/0ffa51ee088f58c44fb0257916f9a231a03d8976/background.js#L254)  in `background.js`:

````js
// set "access-control-allow-origin", prioritize "origin" else "*"
transaction.responseHeaders['access-control-allow-origin'].value =
    transaction.requestHeaders['origin']
    && transaction.requestHeaders['origin'].value !== null
        ? transaction.requestHeaders['origin'].value
        : '*';
````

And at line [279](https://github.com/spenibus/cors-everywhere-firefox-addon/blob/0ffa51ee088f58c44fb0257916f9a231a03d8976/background.js#L279), we override `access-control-allow-credentials` to make it true:

````js
// set "access-control-allow-credentials"
transaction.responseHeaders['access-control-allow-credentials'].value = "true";
````

**Comment by linev** [comment]
Yes, seems to be it works properly. 
Thanks for response.
