### ISSUE TITLE
Specifying local file in whitelist regex

### ISSUE THREAD

**Issue by tinybutch** [spenibus/cors-everywhere-firefox-addon#60]
Hi @spenibus,

I have small Web project which located on PC at C:\www\index.html. It uses third party endpoint by fetching data in Javascript and this endpoint has CORS enabled. When I turned on CORS everywhere Firefox addon, my script can fetch data from this endpoint. But when I tried to add local file by URI which Firefox use:
file:///C:/www/index.html
or just path C:/www/index.html to whitelist in CORS everywhere, it stopped working.

Could you please clarify how local file URL should look like in whitelist regex in this case?

**Comment by spenibus** [comment]
You need a fully formed regex, this should work:
````
/^file:\/\/\/C:\/www\/index.html/i
````
Or you can whitelist the entire folder:
````
/^file:\/\/\/C:\/www\//i
````
Or all local files:
````
/^file:/i
````
Escaping the slashes is quite important, and there's generally a lot of them in urls.

**Comment by tinybutch** [comment]
Thank you! This regex fixed my issue.
