### ISSUE TITLE
Does Not Work on FF 50.

### ISSUE THREAD

**Issue by 2011413125** [spenibus/cors-everywhere-firefox-addon#9]
Hi,
I have been using this addon since 2015. But suddenly when FF got updated to version 50. CORS no longer works. I am doing development with gulp serve and asp.net web api on backend. (The same works on chrome with disabled security). Here is the message i get 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:63744/api/test/testmethod. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).

Following are my reponse headers.
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Headers: authorization, *
> Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
> Access-Control-Allow-Origin: http://localhost:3000, *

**Comment by spenibus** [comment]
I don't remember much, but I'm pretty sure this syntax is invalid:

    Access-Control-Allow-Origin: http://localhost:3000, *

You can't use the wildcard with credentials and you can't specify more than one origin.

> The origin parameter specifies a URI that may access the resource. The browser must enforce this. For requests without credentials, the server may specify "*" as a wildcard, thereby allowing any origin to access the resource.

Source: [Access-Control-Allow-Origin on MDN][1]

The only way the addon could return this value would be that you set it in your request with `Origin`. See the [code here][2] that generates the response:

    // set "Access-Control-Allow-Origin"
    // prioritize "Origin" else "*"
    httpChannel.setResponseHeader(
        'Access-Control-Allow-Origin',
        reqHeaders['Origin'] !== null
            ? reqHeaders['Origin']
            : '*',
        false
    );

Now I feel that this might be a misunderstanding of what this addon actually does.

 - In Chrome, you can disable security and it will ignore errors related to CORS.
 - In Firefox, you can't disable security. The addon simply tricks the browser into thinking the server responded positively to your request, which means the request must still be valid.

The only odd thing about this would be that it worked before version 50, which sounds more like a coincidence.

[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Origin
[2]: https://github.com/spenibus/cors-everywhere-firefox-addon/blob/master/content/module.js#L168
